using System.Data.Entity;
using Abstractor.Cqrs.EntityFramework.Interfaces;
using Abstractor.Cqrs.Interfaces.CrossCuttingConcerns;

namespace AbstractorSamples.Persistence.EntityFramework.Contexts
{
    public class ApplicationDbContext : DbContext, IEntityFrameworkContext
    {
        public ApplicationDbContext(ILogger logger)
            : base("ApplicationDbConnectionString")
        {
            if (logger == null) return;

            // Enables the logging of the SQL commands and queries generated by Entity Framework
            // Uses the ILogger interface provided by the framework
            Database.Log = logger.Log;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            // Uses reflection to discover all the entity mapping configurations into this assembly
            // In this sample, discovers the ItemModelConfiguration

            modelBuilder.Configurations.AddFromAssembly(GetType().Assembly);
        }
    }
}